# fly.toml app configuration file generated for cedit-bots-serene-fire-2998 on 2026-06-04T03:50:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cedit-bots-serene-fire-2998'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile.bots'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
